################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "http://examplesite.org"
title = "KDK Property Services"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = ["zh"]
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""


############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.83.1"


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false


################################# Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "150px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "+44 7783 880436"
email = "info@kdkpropertyservices.co.uk"
# location = "aaa"
image = "images/marker.png"
# **Themefisher**
# North Main Street  
# Brooklyn, New South Wales  
# Australia
# """
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false


[params.contact.form]
enable = false
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = true
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "53.04435633242677"
map_longitude = "-2.9826631288632837"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = true
expire_days = 2


################################# counter.dev analytics #######################
# This is a [privacy-friendly alternative](https://counter.dev/privacy.html) to Google Analytics & Co.
[params.counter]
enable = true
# counter.dev username, see https://counter.dev/setup.html
username = ""


################################# Social Media ################################
# [[params.social]]
# icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
copyright = "info@kdkpropertyservices.co.uk /  +44 7783 880436 /  Copyright &copy; 2021 By [Jiyu](https://yanjiyu.com)"

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
 [[languages.en.menu.main]]
 hasChildren = true
 name = "Services"
 weight = 3

# Footer menu
#[[languages.en.menu.footer]]
#name = "About"
#URL = "about"
#weight = 1

[[languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[languages.en.menu.footer]]
name = "House buying"
URL = "house-buying"
weight = 3

[[languages.en.menu.footer]]
name = "Refurbishment"
URL = "refurbishment"
weight = 4

[[languages.en.menu.footer]]
name = "Maintainence"
URL = "maintainence"
weight = 5

#[[languages.en.menu.footer]]
#name = "Pricing"
#URL = "pricing"
#weight = 4

#[[languages.en.menu.footer]]
#name = "FAQ"
#URL = "faq"
#weight = 5

[[languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


################################# Simplified Chinese translation ##########################
[languages.zh]
languageName = "简体中文"
languageCode = "zh"
contentDir = "content/chinese_simplified"
weight = 2
copyright = "Copyright &copy; 2021 By Jiyu"

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
 [[languages.zh.menu.main]]
 hasChildren = true
 name = "服務"
 weight = 3

# Footer menu
#[[languages.zh.menu.footer]]
#name = "About"
#URL = "about"
#weight = 1

[[languages.zh.menu.footer]]
name = "项目"
URL = "project"
weight = 2

[[languages.zh.menu.footer]]
name = "买房"
URL = "house-buying"
weight = 3

[[languages.zh.menu.footer]]
name = "Refurbishment"
URL = "refurbishment"
weight = 4

[[languages.zh.menu.footer]]
name = "Maintainence"
URL = "maintainence"
weight = 5

#[[languages.zh.menu.footer]]
#name = "Pricing"
#URL = "pricing"
#weight = 4

#[[languages.zh.menu.footer]]
#name = "FAQ"
#URL = "faq"
#weight = 5

[[languages.zh.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


################################# Traditional Chinese translation ##########################
[languages.zhf]
languageName = "中文"
languageCode = "zhf"
contentDir = "content/chinese_traditional"
weight = 2
copyright = "Copyright &copy; 2021 By [Jiyu](https://yanjiyu.com)"

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
 [[languages.zhf.menu.main]]
 hasChildren = true
 name = "服務"
 weight = 4

# Footer menu
#[[languages.zhf.menu.footer]]
#name = "About"
#URL = "about"
#weight = 1

[[languages.zhf.menu.footer]]
name = "項目展示"
URL = "project"
weight = 2

[[languages.zhf.menu.footer]]
name = "買房"
URL = "house-buying"
weight = 3

[[languages.zhf.menu.footer]]
name = "擴建翻新"
URL = "refurbishment"
weight = 4

[[languages.zhf.menu.footer]]
name = "管理維護"
URL = "maintainence"
weight = 5

#[[languages.zhf.menu.footer]]
#name = "Pricing"
#URL = "pricing"
#weight = 4

#[[languages.zhf.menu.footer]]
#name = "FAQ"
#URL = "faq"
#weight = 5

[[languages.zhf.menu.footer]]
name = "聯係我們"
URL = "contact"
weight = 6
